// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CancelConversion() {
  return window['go']['main']['App']['CancelConversion']();
}

export function CheckFFmpeg() {
  return window['go']['main']['App']['CheckFFmpeg']();
}

export function GetMediaInfo(arg1) {
  return window['go']['main']['App']['GetMediaInfo'](arg1);
}

export function SelectInputFile() {
  return window['go']['main']['App']['SelectInputFile']();
}

export function SelectOutputFile(arg1, arg2) {
  return window['go']['main']['App']['SelectOutputFile'](arg1, arg2);
}

export function SetupFFmpeg() {
  return window['go']['main']['App']['SetupFFmpeg']();
}

export function StartConversion(arg1) {
  return window['go']['main']['App']['StartConversion'](arg1);
}
