// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function CancelConversion():Promise<void>;

export function CheckFFmpeg():Promise<boolean>;

export function GetMediaInfo(arg1:string):Promise<main.MediaInfo>;

export function SelectInputFile():Promise<string>;

export function SelectOutputFile(arg1:string,arg2:string):Promise<string>;

export function SetupFFmpeg():Promise<void>;

export function StartConversion(arg1:main.ConversionParams):Promise<void>;
